name: example-environment
channels:
  - conda-forge
dependencies:
  - python
  - numpy
  - pandas
  - matplotlib
#  - bokeh
#  - basemap
#  - ipyleaflet
#  - psutil
#  - toolz
#  - dill
#  - partd
#  - dask
